language: ruby
cache: bundler
rvm:
  - 2.4
install:
  - eval "$(gimme 1.8)"
  - go get github.com/ValeLint/vale
  - bundle install --jobs=3
  - pip install --user yamllint
before_script:
  - yamllint -c '.yamllint.yml' Microsoft
script:
  - cucumber
